apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cp
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: bgp-cplane-dev-v4-control-plane
  bgpInstances:
    - name: cp
      localASN: 65001
      peers:
      - name: frr-router0
        peerAddress: 10.0.1.1
        peerASN: 65000

